#!/usr/bin/env python3
"""
merge_tabula.py

Collapses Tabula-extracted bank-statement rows: text that wrapped onto
continuation ("hanging") rows is merged back into the parent transaction row.

Pattern handled
---------------
A real transaction row has a parseable DATE in the first column. Any following
row(s) WITHOUT a date are continuation lines whose Narration text (and, rarely,
a wrapped Chq./Ref.No. fragment) belong to the transaction directly above.

Usage (CLI)
-----------
    python merge_tabula.py INPUT.xlsx [-o OUTPUT.xlsx] [--sep " "]

If -o is omitted, writes <input>_merged.xlsx next to the input.
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

import openpyxl


COL_DATE = 1
COL_NARRATION = 2
COL_REF = 3
COL_VALUEDT = 4
COL_WITHDRAWAL = 5
COL_DEPOSIT = 6
COL_BALANCE = 7

DATE_TEXT_RE = re.compile(r"^\s*\d{1,2}[-/]\d{1,2}[-/]\d{2,4}\s*$")


def is_date(value):
    if isinstance(value, (datetime.datetime, datetime.date)):
        return True
    if isinstance(value, str) and DATE_TEXT_RE.match(value):
        return True
    return False


def is_blank(value):
    return value is None or (isinstance(value, str) and value.strip() == "")


def looks_like_footer(row_vals):
    joined = " ".join(str(v) for v in row_vals if not is_blank(v)).lower()
    if not joined:
        return False
    markers = (
        "computer generated statement",
        "does not require signature",
        "requesting branch code",
        "statement summary",
        "generated on:",
        "generated by:",
    )
    if any(m in joined for m in markers):
        return True
    if "opening balance" in joined and "count" in joined:
        return True
    if "closing bal" in joined and "debit" in joined:
        return True
    return False


def merge_statement(in_path: Path, out_path: Path, sep: str = " "):
    wb = openpyxl.load_workbook(in_path, data_only=True)
    ws = wb.active
    max_col = ws.max_column

    rows = []
    for r in range(1, ws.max_row + 1):
        vals = [ws.cell(row=r, column=c).value for c in range(1, max_col + 1)]
        if all(is_blank(v) for v in vals):
            continue
        rows.append(vals)

    if not rows:
        raise ValueError("No data rows found in the Tabula-extracted workbook.")

    header = rows[0]
    body = rows[1:]

    merged = []
    dropped_footer = 0
    orphan_lines = 0
    current = None
    in_footer = False

    def flush():
        nonlocal current
        if current is not None:
            if isinstance(current[COL_NARRATION - 1], str):
                current[COL_NARRATION - 1] = re.sub(
                    r"\s+", " ", current[COL_NARRATION - 1]
                ).strip()
            merged.append(current)
            current = None

    for vals in body:
        if in_footer:
            dropped_footer += 1
            continue
        if vals[COL_DATE - 1] == header[COL_DATE - 1] and not is_date(
            vals[COL_DATE - 1]
        ):
            continue
        if looks_like_footer(vals):
            flush()
            in_footer = True
            dropped_footer += 1
            continue

        if is_date(vals[COL_DATE - 1]):
            flush()
            current = list(vals)
        else:
            if current is None:
                merged.append(list(vals))
                orphan_lines += 1
                continue
            frag = vals[COL_NARRATION - 1]
            if not is_blank(frag):
                base = current[COL_NARRATION - 1]
                base = "" if is_blank(base) else str(base)
                current[COL_NARRATION - 1] = (base + sep + str(frag)).strip()
            ref_frag = vals[COL_REF - 1]
            if not is_blank(ref_frag):
                base = current[COL_REF - 1]
                base = "" if is_blank(base) else str(base)
                current[COL_REF - 1] = (base + str(ref_frag)).strip()
            vdt_frag = vals[COL_VALUEDT - 1]
            if not is_blank(vdt_frag) and not is_date(vdt_frag):
                base = current[COL_REF - 1]
                base = "" if is_blank(base) else str(base)
                current[COL_REF - 1] = (base + str(vdt_frag)).strip()

    flush()

    out_wb = openpyxl.Workbook()
    out_ws = out_wb.active
    out_ws.title = ws.title[:31]
    out_ws.append(header)
    for row in merged:
        out_ws.append(row)
    out_wb.save(out_path)

    return {
        "input_rows": len(rows),
        "merged_transactions": len(merged),
        "dropped_footer": dropped_footer,
        "orphan_lines": orphan_lines,
    }


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("input", help="Tabula-extracted .xlsx statement")
    ap.add_argument("-o", "--output", help="output .xlsx (default: <input>_merged.xlsx)")
    ap.add_argument(
        "--sep",
        default=" ",
        help="separator between merged narration fragments (default: space)",
    )
    args = ap.parse_args()

    in_path = Path(args.input).expanduser()
    if not in_path.exists():
        sys.exit(f"File not found: {in_path}")
    out_path = (
        Path(args.output).expanduser()
        if args.output
        else in_path.with_name(in_path.stem + "_merged.xlsx")
    )
    stats = merge_statement(in_path, out_path, sep=args.sep)
    print(f"Input rows (non-empty):  {stats['input_rows']}")
    print(f"Merged transactions:     {stats['merged_transactions']}")
    print(f"Footer rows dropped:     {stats['dropped_footer']}")
    print(f"Orphan lines kept:       {stats['orphan_lines']}")
    print(f"Output: {out_path}")


if __name__ == "__main__":
    main()
